# Generated by Django 4.2.5 on 2023-12-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userInfo',
            field=models.TextField(max_length=500, verbose_name='Информация о пользователе'),
        ),
    ]
